export default function getNbaTeamLogoPaths()
{
    const teamLogos = {
        ATL: require('../nba_logos/ATL.png'),
        BKN: require('../nba_logos/BKN.png'),
        BOS: require('../nba_logos/BOS.png'),
        CHA: require('../nba_logos/CHA.png'),
        CHI: require('../nba_logos/CHI.png'),
        CLE: require('../nba_logos/CLE.png'),
        DAL: require('../nba_logos/DAL.png'),
        DEN: require('../nba_logos/DEN.png'),
        DET: require('../nba_logos/DET.png'),
        GSW: require('../nba_logos/GSW.png'),
        HOU: require('../nba_logos/HOU.png'),
        IND: require('../nba_logos/IND.png'),
        LAC: require('../nba_logos/LAC.png'),
        LAL: require('../nba_logos/LAL.png'),
        MEM: require('../nba_logos/MEM.png'),
        MIA: require('../nba_logos/MIA.png'),
        MIL: require('../nba_logos/MIL.png'),
        MIN: require('../nba_logos/MIN.png'),
        NOP: require('../nba_logos/NOP.png'),
        NYK: require('../nba_logos/NYK.png'),
        OKC: require('../nba_logos/OKC.png'),
        ORL: require('../nba_logos/ORL.png'),
        PHI: require('../nba_logos/PHI.png'),
        PHX: require('../nba_logos/PHX.png'),
        POR: require('../nba_logos/POR.png'),
        SAC: require('../nba_logos/SAC.png'),
        SAS: require('../nba_logos/SAS.png'),
        TOR: require('../nba_logos/TOR.png'),
        UTA: require('../nba_logos/UTA.png'),
        WAS: require('../nba_logos/WAS.png'),
    };
    return teamLogos;
}